export const LOAD_ALBUMS_SUCCESS = 'LOAD_ALBUMS_SUCCESS';
export const LOAD_ALBUMS_FAILED = 'LOAD_ALBUMS_FAILED';

export const LOAD_THUMBNAILS_SUCCESS = 'LOAD_THUMBNAILS_SUCCESS';
export const LOAD_THUMBNAILS_FAILED = 'LOAD_THUMBNAILS_FAILED';

